#!/bin/bash

test_exam_dir=$(pwd)
script_to_check_results=$test_exam_dir/callme

echo
echo -e "\e[1;35m $(date) \e[0m"
echo

for i in *.com

  do

     if [ -e ${test_exam_dir}/${i%.com} ]
       then
         echo -e "\e[1;31m An existing ${i%.com}" \
              "directory found. Deleting it now. \e[0m"
	 rm -rf ${test_exam_dir}/${i%.com}
     fi

  done

echo
echo "An empty directory is being created for:"
echo

for i in *.com

  do

     echo -e "\e[1;36m  ---- ${i%.com} ---- \e[0m"
     mkdir ${test_exam_dir}/${i%.com}

  done   

echo
echo "Done creating directories. Running the tests now."
echo

for i in *.com

  do

     echo -e "\e[1;32m   ---- Testing $i ---- \e[0m"
     ../effhess.x $i > ${i%.com}.log ; rm *.log
     term_ok=$(grep -i "Effective Hessian terminated normally." ${i%.com}.out | wc -l)

     if [ $term_ok -eq 1 ] 
      then
         mv ${i%.com}.out *.rc *.nast ${test_exam_dir}/${i%.com}
         $script_to_check_results $i ${test_exam_dir}/${i%.com}
         
         check_result=$(echo $?)

         if [ $check_result -ne 0 ] ; then
          echo "............................ Failed"
         else
          echo "............................ Passed"
         fi

      else
        echo
        echo "The ${i%.com} test didn't terminate normally."
        echo "Check $i for errors and come back. Continue with other tests now."
        echo
        continue
     fi

  done

echo
echo Done with tests
echo
