#!/bin/bash

name=$1
out_dir=$2
ierr=0
tmp=0

function compare_two() {

diff=$(echo $1 $2 | awk '{ if($1>$2) print $1-$2 ; else print $2-$1 }')
res=$(echo $diff $3 | awk '{ if($1>$2) print 1 ; else print 0 }')

return $res

}


case $1 in

 exam01_1.inp )
 
 k_TST_1000K_exam01_1=3.20e01 ; tol=0.5

 k_TST_1000K=$(grep -m1 " 1000.0 " $out_dir/nast.out | awk '{ printf "%12.10e\n", $2 }')

 compare_two $k_TST_1000K_exam01_1 $k_TST_1000K $tol ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0

    ;;

 exam01_2.inp )
 
 k_TST_1000K_exam01_2=1.54e01 ; tol=0.5

 k_TST_1000K=$(grep -m1 " 1000.0 " $out_dir/nast.out | awk '{ printf "%12.10e\n", $2 }')

 compare_two $k_TST_1000K_exam01_2 $k_TST_1000K $tol ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0

    ;;

 exam02_1.inp )
 
 k_TST_1000K_exam02_1=6.48e-02 ; tol1=0.02
 k_TST_2000K_exam02_1=1.14e05 ;  tol2=1e04

 # >>>> For debugging >>>>
 # >>>> Rovibrational density of reactants at eps = 1500 cm-1 >>>>

 dosR_exam02_1=14128.8782209 ; tol3=5.0
 
 k_TST_1000K=$(grep -m1 " 1000.0 " $out_dir/nast.out | awk '{ print $2 }')
 k_TST_2000K=$(grep -m1 " 2000.0 " $out_dir/nast.out | awk '{ print $2 }')
 dosR=$(grep " 1500 " $out_dir/dos_reactant.out | awk '{ print $4}')

 compare_two $k_TST_1000K_exam02_1 $k_TST_1000K $tol1 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_TST_2000K_exam02_1 $k_TST_2000K $tol2 ; tmp=$(echo $?) ;  ierr=$((ierr + tmp)) ; tmp=0
 compare_two $dosR_exam02_1 $dosR $tol3 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0

    ;;

 exam02_2.inp )
 
 k_TST_1000K_exam02_2=1.37e-02 ;  tol1=0.02
 k_TST_2000K_exam02_2=2.67e04  ;  tol2=1e04

 # >>>> For debugging >>>>
 # >>>> Rovibrational density of MECP at eps = 22991 cm-1 >>>>

 dosMECP_exam02_2=5544.07 ; tol3=5.0
 
 k_TST_1000K=$(grep -m1 " 1000.0 " $out_dir/nast.out | awk '{ print $2 }')
 k_TST_2000K=$(grep -m1 " 2000.0 " $out_dir/nast.out | awk '{ print $2 }')
 dosMECP=$(grep "22991 " $out_dir/dos_mecp.out | awk '{ print $4}')
 compare_two $k_TST_1000K_exam02_2 $k_TST_1000K $tol1 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_TST_2000K_exam02_2 $k_TST_2000K $tol2 ; tmp=$(echo $?) ;  ierr=$((ierr + tmp)) ; tmp=0
 compare_two $dosMECP_exam02_2 $dosMECP $tol3 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0

    ;;
 
 exam03.inp )
 
 k_LZ_295_exam03=1.06e01           ; tol1=0.2
 k_WC_295_exam03=5.21e06           ; tol2=1e4
 p_LZ_MB_295_exam03=0.25039e-01    ; tol3=0.005
 p_LZ_Kuki_295_exam03=0.6555e-02   ; tol4=0.0005

 # >>>> For debugging >>>>
 # >>>> Rovibrational density of reactants at eps = 912 cm-1 >>>>

 dosR_exam03=4.076548e01 ; tol5=2.0

 k_LZ_295=$(grep -m1 " 295.0 " $out_dir/nast.out | awk '{ print $2 }')
 k_WC_295=$(grep -m1 " 295.0 " $out_dir/nast.out | awk '{ print $3 }')
 p_LZ_MB_295=$(grep -m2 " 295.0 " $out_dir/nast.out | tail -n1 | awk '{ print $2}')
 p_LZ_Kuki_295=$(grep -m2 " 295.0 " $out_dir/nast.out | tail -n1 | awk '{ print $3}') 
 dosR=$(grep " 912 " $out_dir/dos_reactant.out | awk '{ print $4}')

 compare_two $k_LZ_295_exam03 $k_LZ_295 $tol1 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_WC_295_exam03 $k_WC_295 $tol2 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $p_LZ_MB_295_exam03 $p_LZ_MB_295 $tol3 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $p_LZ_Kuki_295_exam03 $p_LZ_Kuki_295 $tol4 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $dosR_exam03 $dosR $tol5 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0

    ;;

 exam04.inp )
    
 k_LZ_296_exam04_direct=1.76e06 ; tol1=1e04
 k_WC_296_exam04_direct=4.96e06  ; tol2=$tol1
 k_LZ_296_exam04_reverse=8.76e01    ; tol3=1.0
 k_WC_296_exam04_reverse=3.50e02    ; tol4=2.0
 
 k_LZ_296_direct=$(grep -m1 " 296.0 " $out_dir/nast.out | awk '{ print $2 }')
 k_WC_296_direct=$(grep -m1 " 296.0 " $out_dir/nast.out | awk '{ print $3 }')
 k_LZ_296_reverse=$(grep -m3 " 296.0 " $out_dir/nast.out | tail -n1 | awk '{ print $2}')
 k_WC_296_reverse=$(grep -m3 " 296.0 " $out_dir/nast.out | tail -n1 | awk '{ print $3}') 

 compare_two $k_LZ_296_exam04_direct $k_LZ_296_direct $tol1 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_WC_296_exam04_direct $k_WC_296_direct $tol2 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_LZ_296_exam04_reverse $k_LZ_296_reverse $tol3 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_WC_296_exam04_reverse $k_WC_296_reverse $tol4 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
    
    ;;

 exam05.inp )
 
 k_WC_247cm_exam05=1.66e08  ; tol1=2e06
 k_ZN_247cm_exam05=7.14e04  ; tol2=2e02
 k_WC_494cm_exam05=4.31e08  ; tol3=$tol1
 k_ZN_494cm_exam05=6.28e05  ; tol4=2e03
 

 # >>>> For debugging >>>>
 # >>>> Rovibrational density of reactants at eps = 1000 cm-1 >>>>

 dosR_exam05=29762.7509 ; tol5=5.0

 k_WC_247cm=$(grep -m1 " 247 " $out_dir/energy_rates.out | awk '{ print $3 }')
 k_ZN_247cm=$(grep -m1 " 247 " $out_dir/energy_rates.out | awk '{ print $4 }')
 k_WC_494cm=$(grep -m1 " 494 " $out_dir/energy_rates.out | awk '{ print $3 }')
 k_ZN_494cm=$(grep -m1 " 494 " $out_dir/energy_rates.out | awk '{ print $4 }') 
 dosR=$(grep " 1000 " $out_dir/dos_reactant.out | awk '{ print $4}')

 compare_two $k_WC_247cm_exam05 $k_WC_247cm $tol1 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_ZN_247cm_exam05 $k_ZN_247cm $tol2 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_WC_494cm_exam05 $k_WC_494cm $tol3 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_ZN_494cm_exam05 $k_ZN_494cm $tol4 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $dosR_exam05 $dosR $tol5 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
    
    ;;

 exam06.inp )
 
 k_WC_900_exam06=1.05e08 ; tol1=1e6
 k_ZN_900_exam06=2.09e07 ; tol2=1e5
 k_WC_1000_exam06=1.24e08 ; tol3=$tol1
 k_ZN_1000_exam06=3.07e07 ; tol4=$tol2

 # >>>> For debugging >>>>
 # >>>> Rovibrational density of turning point at eps = 1153 cm-1 >>>>
 dosTP_exam06=639.9154827 ; tol5=2.0

 k_WC_900=$(grep -m1 " 900.0 " $out_dir/nast.out | awk '{ print $3 }')
 k_ZN_900=$(grep -m1 " 900.0 " $out_dir/nast.out | awk '{ print $4 }')
 k_WC_1000=$(grep -m1 " 1000.0 " $out_dir/nast.out | awk '{ print $3}')
 k_ZN_1000=$(grep -m1 " 1000.0 " $out_dir/nast.out | awk '{ print $4}') 
 dosTP=$(grep " 1153 " $out_dir/dos_tp.out | awk '{ print $4}')

 compare_two $k_WC_900_exam06 $k_WC_900 $tol1 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_ZN_900_exam06 $k_ZN_900 $tol2 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_WC_1000_exam06 $k_WC_1000 $tol3 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_ZN_1000_exam06 $k_ZN_1000 $tol4 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $dosTP_exam06 $dosTP $tol5 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
    
    ;;

 exam07.inp )

 LZS_220_1_ex07=2.2551e-02 ; tol1=0.001
 LZS_220_2_ex07=0.1849     ; tol2=$tol1
 k_221_1_ex07=1.51e07      ; tol3=1e05
 k_221_2_ex07=1.28e08      ; tol4=1e06

 LZS_220_1=$(grep -m1 " 220 " $out_dir/split_probabilities.out | awk '{ print $2 }')
 LZS_220_2=$(grep -m1 " 220 " $out_dir/split_probabilities.out | awk '{ print $3 }')
 k_221_1=$(grep -m1 " 221 " $out_dir/split_energy_rate.out | awk '{ print $2 }')
 k_221_2=$(grep -m1 " 221 " $out_dir/split_energy_rate.out | awk '{ print $3 }')

 compare_two $LZS_220_1_ex07 $LZS_220_1 $tol1 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $LZS_220_2_ex07 $LZS_220_2 $tol2 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_221_1_ex07   $k_221_1   $tol3 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
 compare_two $k_221_2_ex07   $k_221_2   $tol4 ; tmp=$(echo $?) ; ierr=$((ierr + tmp)) ; tmp=0
   
   ;;

 * )
    echo "Unrecognized file"

 ierr=1

    ;;

esac

exit $ierr
